name: Go CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.24.x']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install dependencies
      run: go mod download

    - name: Run tests
      run: |
        # Запускаем сервер в фоновом режиме. Обратите внимание на правильный путь!
        go run ./cmd/main.go &
        timeout 30s bash -c 'until curl -s http://localhost:7540 > /dev/null; do echo "Waiting for server..."; sleep 1; done'

        # Запускаем все тесты
        go test -v ./tests

